[project]
name = "stonks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo==4.10.1",
    "requests==2.32.3",
    "websocket-client==1.8.0",
]
